# ===========================================
# Animan - Configuration
# ===========================================

server.port=8080

# --- Site cible ---
animan.base-url=https://w16.french-manga.net
animan.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

# --- Telechargement ---
animan.download-dir=${user.home}/Downloads/Animan
animan.max-concurrent-downloads=3
animan.connection-timeout=15000
animan.read-timeout=30000

# --- Thymeleaf ---
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# --- Logging ---
logging.level.com.pauldev.animan=DEBUG
